executor: "KubernetesExecutor"

# Images
images:
  airflow:
    repository: my-dags # Local development - override with ECR for production
    tag: ~
    # Specifying digest takes precedence over tag.
    digest: ~
    pullPolicy: IfNotPresent

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent

dags:
  persistence:
    enabled: false # Don't mount DAGs from Docker image
  gitSync:
    enabled: true
    repo: https://github.com/Binh-SPU/databricks-airflow.git
    branch: main
    ref: main
    depth: 1
    maxFailures: 0
    subPath: "dags"
    credentialsSecret: git-credentials

logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: True
    # If using a custom storageClass, pass name here
    storageClassName: manual
    ## the name of an existing PVC to use
    existingClaim: airflow-logs-pvc
