apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      # Create a mount on my local machine to the container host
      # For Docker Desktop on Windows with WSL2, use this format:
      - hostPath: /run/desktop/mnt/host/c/Users/phamb/Projects/databricks-airflow/tmp/logs
        containerPath: /mnt/airflow-data/logs
