name: Push Airflow Image to ECR
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          IMAGE_NAME=my-dags-repo
          ECR_REPO=${{ secrets.ECR_REGISTRY }}/$IMAGE_NAME

          # Build and tag image
          docker build --pull --tag $ECR_REPO:$IMAGE_TAG --tag $ECR_REPO:latest -f cicd/Dockerfile .

          # Push both tags
          docker push $ECR_REPO:$IMAGE_TAG
          docker push $ECR_REPO:latest

          echo "Pushed: $ECR_REPO:$IMAGE_TAG"
          echo "Pushed: $ECR_REPO:latest"
